name: 🆕 Feature Request
description: Suggest a new feature or improvement to an existing one.
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking your time to help us make our works better and more stable!
  - type: input
    id: content
    attributes:
      label: Contact Details
      description: How may we get in touch if we need more info?
      placeholder: "email@example.com"
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What's the problem?
      description: What's the problem to be solved here? E.g., "I'm frustrated when..."
    validations:
      required: true
  - type: textarea
    id: suggested-change
    attributes:
      label: What do you suggest?
      description: If you have something in mind, what's your suggested improvement?
    validations:
      required: false
  - type: textarea
    id: extra-context
    attributes:
      label: Extra context?
      description: Is there anything else we should know to help implement this change?
    validations:
      required: false
  - type: textarea
    id: workarounds
    attributes:
      label: Any workarounds?
      description: Are there alternatives or workarounds to solve the problem you're describing?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Do you accept the Code of Conduct?
      description: By submitting this report, you agree to follow our
        [Code of Conduct](https://github.com/teaminkling/.github/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow Inkling Interactive's Code of Conduct.
          required: true
