name: 💥 Problem Report
description: File a problem report for bugs, typos, inaccuracies, and so on.
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking your time to help us make our works better and more stable!
  - type: input
    id: content
    attributes:
      label: Contact Details
      description: How may we get in touch if we need more info?
      placeholder: email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What went wrong? What did you expect to happen? Please provide screenshots or videos if you can!
    validations:
      required: true
  - type: textarea
    id: extra-context
    attributes:
      label: Extra context?
      description: Is there anything else we should know? Logs? Environments, e.g., Chrome Stable, macOS 12.3.1 ARM64?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Do you accept the Code of Conduct?
      description: By submitting this report, you agree to follow our
        [Code of Conduct](https://github.com/teaminkling/.github/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow Inkling Interactive's Code of Conduct.
          required: true
