name: "Branch on Issue"
on:
  issues:
    types: [assigned]

# Create a new branch for every single assigned issue.

jobs:
  issue-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Create Issue Branch
      uses: robvanderleek/create-issue-branch@v1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
